apiVersion: v1
kind: Service
metadata:
  name: angple-api
  namespace: angple
  labels:
    app.kubernetes.io/name: angple-api
    app.kubernetes.io/part-of: angple
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: angple-api
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
